apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: chickadee-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/chickadee-dotnet-basic-gitops